name: leen_alkhier_store
description: A new Flutter project.
# this app use flutter_windows_2.10.4-stable

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  app_settings: ^4.1.6
  shared_preferences: ^2.0.5
  provider: ^6.0.2 #^4.3.3
  flutter_screenutil: any
  country_code_picker: ^2.0.2
  persistent_bottom_nav_bar: ^4.0.2
  email_validator: ^2.0.1
  file_picker: ^4.6.1
  google_maps_flutter: ^2.1.8
  location: ^4.4.0
  flutter_spinkit: ^5.1.0
  # flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  fluttertoast: ^8.0.9
#  flutter_restart: any
  form_validator: ^1.0.2
  firebase_messaging: ^11.2.6
  firebase_core: any
  firebase_analytics: ^9.1.9
  flutter_local_notifications: ^9.5.2
  url_launcher: ^6.1.0
  scroll_to_index: ^2.1.1
  rxdart: ^0.27.5
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  geolocator: ^8.2.1
  get: ^4.6.1
  flutter_rating_bar: ^4.0.1
  flutter_geocoder: ^0.2.2-nullsafety
  table_calendar: ^3.0.6
  package_info_plus: ^1.4.2
  http_parser: ^4.0.1
  win32: ^2.5.2
  carousel_slider:  ^4.1.1
  charts_flutter: ^0.12.0
  pin_code_fields: ^7.3.0
  flutter_otp_text_field: ^1.1.1
  dotted_border: ^2.0.0+1
  flutter_localizations:
     sdk: flutter
  localize_and_translate:
  font_awesome_flutter:
  webview_flutter: 2.0.13
  dropdown_search:
  dio:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_html: ^2.2.1
  multi_image_picker: ^4.8.01
#  flutter_absolute_path:
  lecle_flutter_absolute_path: ^0.0.1+3
  video_player: ^2.4.5
  image_picker: ^0.7.3
  flutter_offline:
  custom_radio_group_list:
  flutter_native_image:
  mime:
  flutter_pdfview:
  path_provider:
  flutter_statusbarcolor_ns:
  page_transition:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_img.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - i18n/ar.json
    - i18n/en.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Jannat
      fonts:
        - asset: fonts/a_jannat.ttf
    - family: Mon
      fonts:
        - asset: fonts/Montserrat.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
